### ISSUE TITLE
Error loading zoautil.so

### ISSUE THREAD

**Issue by rinaldou** [IBM/zoau#2]
We installed zoau and open python 3.9 on z/OS 2.4. 
When I tried to run a ansible job (from the examples, just to test), it gives me the following error:

fatal: [zostcpip02]: FAILED! => {"changed": false, "module_stderr": "Shared connection to x.x.x.x closed.\r\n", "module_stdout": "CEE3501S The module zoautil.so was not found.\r\n         From compile unit TOROLABA:./Python/dynload_shlib.c at entry point _PyImport_FindSharedFuncptr at statement 100 at compile unit offset +000000003814C798 at entry offset +0000000000000290 at address 000000003814C798.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}

The problem is that the LIBPATH environment variable is set with the directory which has zoautil.so.

I am not too familiar with omvs, in RedHat, whenever a new lib is inserted, I need to run a 'lddconfig' to the system starts seeing the new module. Is there anything similiar to omvs, or just adding the directory with the lib in $LIBPATH would solve the problem?

**Comment by balkajbaf** [comment]
for purpose of diagnoses, can you directly ssh to your system and setup your env vars and try to import ZOAU from python prompt?
`#>python3
Python 3.8.2 (heads/pyz_dev:ff6af4d9f8, May 21 2020, 10:28:28) on zos
Type "help", "copyright", "credits" or "license" for more information.
>>> from zoautil_py import datasets
>>> 
`
and if that failed please share your `env` output with us.

**Comment by MikeFultonDev** [comment]
@rinaldou please provide some more info so we can help out. The underlying message is occurring because Python is unable to find the DLL zoautil.so.

**Comment by MikeFultonDev** [comment]
I am going to mark this item closed...

**Comment by Shadow2121** [comment]
`from zoautil_py import datasets, jobs, zsystem`
If I use this line of code I am getting the error,
```
Traceback (most recent call last):
  File "members.py", line 3, in <module>
  File "/usr/lpp/IBM/zoautil/lib/zoautil_py/datasets.py", line 4, in <module>
    from zoautil_py.core import call_zoau_library
SystemError: initialization of core did not return an extension module
```

And when I try to use it other way like `zoautil_py.datasets.exists(dsname)` It's giving me the error.
```
Traceback (most recent call last):
  File "members.py", line 11, in <module>
AttributeError: module 'zoautil_py' has no attribute 'datasets'
```

Can you help me with this?

**Comment by WaterSibilantFalling** [comment]
@Shadow2121 and others. 
I did the same exercise and had an equivalent problem.  You have to run the code as `python3 progname.py`, not `python progname`.  Then it works.  

If you search the forum (zxplore forum) you'll for "zoautil" or anything relevant, you'll see lots of people asking equivalent questions.

**Comment by azarrafa** [comment]
Hello,
I'm getting the same error, how did you solved this problem: 
CEE3501S The module zoautil.so was not found
Thanks

**Comment by AnthonyGiorgio** [comment]
It sounds like your LIBPATH isn't pointing to where the ZOAU shared library lives.  Could you check your environment variables?

**Comment by ddimatos** [comment]
This appears to be an old thread from 6-3-21 and is getting updates when its closed, if this is Ansible (collection ibm_zos_core) related, i suggest a [discussion](https://github.com/ansible-collections/ibm_zos_core/discussions) as apposed to a git issue (because this seems configuration related, not a actual bug).

From what I can tell its a miss-configuration:
- How are your environment variables being accessed by the playbook, usually we see/recommend a snippet like this in your playbook `environment: "{{ environment_vars }}"` and then configure something like [this](https://github.com/IBM/z_ansible_collections_samples/tree/main/zos_concepts/program_authorization/git_apf/inventories) for your `group_vars` and `host_vars` which are explained in detail [here](https://github.com/IBM/z_ansible_collections_samples/blob/main/docs/share/zos_core/configuration_guide.md).

If there is followup, please move this to the [ibm_zos_core](https://github.com/ansible-collections/ibm_zos_core) collection repository where that team monitors for Ansible questions. Thank you.

**Comment by azarrafa** [comment]
thanks for this sample. it's working great.
